[package]
name = "eval"
version = "0.4.3"
description = "Expression evaluator"
keywords = ["expression", "evaluate", "evaluator", "expr", "template"]
authors = ["fengcen <fengcen.love@gmail.com>"]
repository = "https://github.com/fengcen/eval.git"
homepage = "https://github.com/fengcen/eval"
documentation = "https://docs.rs/eval"
readme = "README.md"
license = "MIT"

[lib]
name = "eval"
path = "src/lib.rs"

[dependencies]
serde = "1.0.139"
serde_json = "1.0.82"
quick-error = "2.0.1"

[features]
unstable = []
